Lums658/vector bool
pnnl/NWGraph pull request #5
Opened 2022-09-09 21:15 UTC by lums658

Create support to properly deal with vector of bool in our zip container.

2023-03-06 23:51 UTC, lums658 commented
lgtm

2023-03-07 00:08 UTC, mcmillan03 requested changes
Review comments and respond as you see fit.

2023-03-07 00:08 UTC, mcmillan03 commented on include/nwgraph/graph_adaptor.hpp
> +    graph_base::is_open = true;
Should this be false?

2023-03-07 00:08 UTC, mcmillan03 commented on include/nwgraph/graph_adaptor.hpp
> +  auto num_edgees() const {
Is this misspelled?

2023-03-07 00:08 UTC, mcmillan03 commented on include/nwgraph/graph_concepts.hpp
> +//template <min_idx_edge_list T, class U>
remove or add todo

2023-03-07 00:08 UTC, mcmillan03 commented on include/nwgraph/graph_concepts.hpp
> +//template <min_idx_edge_list T, class U>
remove or add todo

2023-03-07 01:31 UTC, lums658 commented on include/nwgraph/graph_adaptor.hpp
> +    graph_base::is_open = true;
Yes, fixed.

2023-03-07 01:31 UTC, lums658 commented on include/nwgraph/graph_concepts.hpp
> +//template <min_idx_edge_list T, class U>
Fixed.

2023-03-07 01:31 UTC, lums658 commented on include/nwgraph/graph_adaptor.hpp
> +  auto num_edgees() const {
Yees.

2023-03-07 01:32 UTC, lums658 commented on include/nwgraph/graph_concepts.hpp
> +//template <min_idx_edge_list T, class U>
Fixed.

2023-03-07 01:33 UTC, lums658 commented
Changes applied.

2026-07-19 19:03 UTC, lums-pnnl commented
Superseded by d129b86 on master, which fixes the underlying `vector<bool>` problem directly — the SoA reference tuple now keeps the `vector<bool>::reference` proxy for mutable access, and the swap machinery knows how to swap through it — and adds `vector_bool_test` as a Catch2 test. The CMake/README portions of this branch landed on master long ago. The `graph_adaptor` edge-list specialization and `min_idx_edge_list` concepts remain unlanded and can be revived separately if still wanted. Closing.

2026-07-19 19:04 UTC, lums658 commented
Superseded by d129b86 on master, which fixes the underlying `vector<bool>` problem directly — the SoA reference tuple now keeps the `vector<bool>::reference` proxy for mutable access, and the swap machinery knows how to swap through it — and adds `vector_bool_test` as a Catch2 test. The CMake/README portions of this branch landed on master long ago. The `graph_adaptor` edge-list specialization and `min_idx_edge_list` concepts remain unlanded and can be revived separately if still wanted. Closing.

2026-07-19 19:04 UTC, closed without merging